name: Trivy
on: [push]
jobs:
  build:
    name: TRIVY Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/falcon_app:latest
#           tags: test_image:latest
          
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/falcon_app:latest
#           image-ref: test_image:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL'

# name: Scan TRIVY
# on: [push, pull_request]
# jobs:
#   scan:
#     name: Scan
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build
#       run: docker build -t trivy-ci-test:1.2.3 .
#     - name: Scan
#       uses: docker://aquasec/trivy
#       with:
#         args: --severity CRITICAL --no-progress trivy-ci-test:1.2.3
